// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShaTask.Models;

public partial class City
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(200)]
    public string CityName { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}